
services:
  postgres:
    image: postgres:latest
    container_name: event-service-db
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_db
    ports:
      - "5433:5432"
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: event-service-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - my_network
    depends_on:
      - postgres

networks:
  my_network:
    driver: bridge
