services:
  postgres:
    image: postgres:latest
    container_name: booking-service-db
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking_db
    ports:
      - "5434:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: booking-service-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - my_network
    depends_on:
      - postgres

networks:
  my_network:
    driver: bridge
volumes:
  postgres_data: